package com.example.reakageapp.data.model

import com.google.firebase.database.Exclude // Used to exclude reportId from being written to DB if it's the key
import com.google.firebase.database.ServerValue // To use server-side timestamps

data class Report(
    @get:Exclude // reportId is often the key of the node, not a field within it
    var reportId: String = "", // Will be set from the Firebase key after fetching

    var userId: String = "",
    var reporterEmail: String = "",
    var timestamp: Any = ServerValue.TIMESTAMP, // Use Any for ServerValue, will be Long when read
    var location: String = "",
    var description: String = "",
    var photoUrl: String? = null,
    var status: String = "submitted",
    var severity: String = "" // Added severity field
) {
    // No-argument constructor is automatically generated by Kotlin if all properties have defaults,
    // which is required by Firebase for deserialization.

    // Helper to get timestamp as Long, as it's stored as Long in Firebase
    fun getTimestampLong(): Long {
        return if (timestamp is Long) timestamp as Long else 0L
    }
}
